apiVersion: v1
kind: Pod
metadata:
  name: pod-with-ssh-keys
spec:
  volumes:
  - name: ssh-keys-volume
    secret:
      secretName: ssh-secret
  containers:
  - name: ssh-server
    image: ubuntu:latest
    command: ["/bin/sh"]
    args: ["-c", "ls /root/.ssh; md5sum /root/.ssh/id_rsa.pub; md5sum /root/.ssh/id_rsa"]
    volumeMounts:
    - name: ssh-keys-volume
      mountPath: "/root/.ssh"