apiVersion: v1
kind: Pod
metadata:
  name: kubectl-create-secret
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    args:
    - create 
    - secret 
    - generic 
    - test
    - --from-literal=literal1=text-for-literal-1
  serviceAccount: secret-admin
  serviceAccountName: secret-admin
