apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    args:
    - get
    - secret
    - opaque-example-from-literals
  serviceAccount: secret-viewer
  serviceAccountName: secret-viewer
