apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox 
    name: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]
  serviceAccountName: example-service-account